<?php

namespace Container7eNiPDN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2MP3eQmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2MP3eQm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2MP3eQm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\OrderController::sortOrderDateAsc' => ['privates', '.service_locator.dcQF4U2', 'get_ServiceLocator_DcQF4U2Service', true],
            'App\\Controller\\OrderController::sortOrderDateDesc' => ['privates', '.service_locator.dcQF4U2', 'get_ServiceLocator_DcQF4U2Service', true],
            'App\\Controller\\ProductController::searchProductByName' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::sortProductIdDesc' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController::sortProductPriceAsc' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.7PhToZy', 'get_ServiceLocator_7PhToZyService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\OrderController:sortOrderDateAsc' => ['privates', '.service_locator.dcQF4U2', 'get_ServiceLocator_DcQF4U2Service', true],
            'App\\Controller\\OrderController:sortOrderDateDesc' => ['privates', '.service_locator.dcQF4U2', 'get_ServiceLocator_DcQF4U2Service', true],
            'App\\Controller\\ProductController:searchProductByName' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:sortProductIdDesc' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductController:sortProductPriceAsc' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.7PhToZy', 'get_ServiceLocator_7PhToZyService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\OrderController::sortOrderDateAsc' => '?',
            'App\\Controller\\OrderController::sortOrderDateDesc' => '?',
            'App\\Controller\\ProductController::searchProductByName' => '?',
            'App\\Controller\\ProductController::sortProductIdDesc' => '?',
            'App\\Controller\\ProductController::sortProductPriceAsc' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\OrderController:sortOrderDateAsc' => '?',
            'App\\Controller\\OrderController:sortOrderDateDesc' => '?',
            'App\\Controller\\ProductController:searchProductByName' => '?',
            'App\\Controller\\ProductController:sortProductIdDesc' => '?',
            'App\\Controller\\ProductController:sortProductPriceAsc' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
